version: "3"
name: monorepo

services:
  client:
    command: ["npm", "start"]
    build:
      context: ./packages/client
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/client:/usr/src/app
      - node_modules_client:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    command: ["npm", "start"]
    build:
      context: ./packages/server
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/server:/usr/src/app
      - node_modules_server:/usr/src/app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=monorepo
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=admin
      - MONGO_AUTH_SOURCE=admin
    ports:
      - 5000:5000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
  node_modules_client:
    driver: local
  node_modules_server:
    driver: local
